site_name: mlr tutorial
site_dir: html
repo_url: https://github.com/berndbischl/mlr/
use_directory_urls: False
theme: 'mkdocs'
theme_dir: 'custom_theme'
pages:
- ["index.md", "Home"]
- ["task.md", "Basics", "Tasks"]
- ["learner.md", "Basics", "Learner"]
- ["train.md", "Basics", "Train"]
- ["predict.md", "Basics", "Predict"]
- ["performance.md", "Basics", "Performance"]
- ["resample.md", "Basics", "Resampling"]
- ["benchmark_experiments.md", "Basics", "Benchmark Experiments"]
- ["parallelization.md", "Basics", "Parallelization"]
- ["configureMlr.md", "Advanced", "Configuration"]
- ["wrapper.md", "Advanced", "Wrapped Learners"]
- ["preproc.md", "Advanced", "Preprocessing"]
- ["impute.md", "Advanced", "Imputations"]
- ["bagging.md", "Advanced", "Bagging"]
- ["tune.md", "Advanced", "Tuning"]
- ["feature_selection.md", "Advanced", "Feature Selection"]
- ["cost_sensitive_classif.md", "Advanced", "Cost-Sensitive Classification"]
- ["over_and_undersampling.md", "Advanced", "Imbalanced Classification Problems"]
- ["roc_analysis.md", "Advanced", "ROC Analysis"]
- ["create_learner.md", "Extend", "Create Custom Learners"]
- ["create_measure.md", "Extend", "Create Custom Measures"]
- ["example_tasks.md", "Appendix", "Example Tasks"]
- ["integrated_learners.md", "Appendix", "Integrated Learners"]
- ["measures.md", "Appendix", "Implemented Performance Measures"]
- ["filter_methods.md", "Appendix", "Integrated Filter Methods"]

