language: r
env:
    global:
        - _R_CHECK_TIMINGS_=0
branches:
    only:
        - master
        - multiFidPlugIn
apt_packages:
    - r-cran-rjava
r_github_packages:
    - mllg/checkmate
    - berndbischl/BBmisc
    - berndbischl/parallelMap
    - berndbischl/ParamHelpers
r_binary_packages:
    - ada
    - adabag
    # - bartMachine
    # - brnn
    - bst
    # - care
    - caret
    - class
    - clue
    - cluster
    - clusterSim
    - clValid
    - cmaes
    - CoxBoost
    - crs
    - Cubist
    - DiceKriging
    # - DiceOptim
    # - DiscriMiner
    - e1071
    - earth
    - elasticnet
    # - elmNN
    - emoa
    # - extraTrees
    - flare
    - FNN
    - frbs
    # - FSelector
    - gbm
    - GenSA
    - ggplot2
    - ggvis
    - glmnet
    - Hmisc
    - irace
    - kernlab
    - kknn
    - klaR
    - knitr
    - kohonen
    # - laGP
    - LiblineaR
    # - lqa
    - MASS
    - mboost
    - mco
    - mda
    - mlbench
    - modeltools
    # - mRMRe
    - nnet
    # - nodeHarvest
    - pamr
    - party
    - penalized
    - pls
    - plyr
    - pROC
    - randomForest
    - randomForestSRC
    - reshape2
    - RCurl
    - rFerns
    - rjson
    - rmarkdown
    - robustbase
    - ROCR
    - rpart
    # - rrlda
    - rsm
    - RWeka
    - sda
    - shiny
    # - sparsediscrim
    # - sparseLDA
    - stepPlr
    - testthat
    - tgp
    - TH.data
before_script:
    # - git clone https://github.com/mllg/travis-r-tools.git travis-r-tools
    # - Rscript travis-r-tools/update-packages.r
    - Rscript -e 'options(repos = "http://cran.rstudio.com"); tryCatch({ old <- old.packages(); if (!is.null(old)) install.packages(old[, "Package"]) }, error = function(e) { message(e); q(status = 1, save = "no") })'
    - sudo R CMD javareconf
    - java -cp /usr/local/lib/R/site-library/RWekajars/java/weka.jar weka.core.WekaPackageManager -install-package thirdparty/XMeans1.0.4.zip
notifications:
  email:
    recipients:
        - bernd_bischl@gmx.net
        - michellang@gmail.com
        - travis.mlr@jakob-r.de
        - larsko@cs.ubc.ca
        - schiffner@math.uni-duesseldorf.de
        - erich.studerus@gmail.com
    on_success: change
    on_failure: always
