# travis config, based on https://github.com/craigcitro/r-travis

language: c
script: travis_wait ./travis-tool.sh run_tests
env: R_CHECK_TIMINGS=0
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh aptget_install r-cran-rjava
  - sudo R CMD javareconf
  - ./travis-tool.sh github_package testthat
  - ./travis-tool.sh github_package assertthat
  - ./travis-tool.sh github_package berndbischl/BBmisc
  - ./travis-tool.sh github_package berndbischl/parallelMap
  - ./travis-tool.sh github_package berndbischl/ParamHelpers
  - ./travis-tool.sh install_deps
  - java -cp /usr/local/lib/R/site-library/RWekajars/java/weka.jar weka.core.WekaPackageManager -install-package XMeans
  - java -cp /usr/local/lib/R/site-library/RWekajars/java/weka.jar weka.core.WekaPackageManager -install-package optics_dbScan
branches:
  except:
   - /-expt$/
notifications:
  email:
    on_success: change
    on_failure: change
after_failure:
  - ./travis-tool.sh dump_logs
