language: r
env:
    global:
        - _R_CHECK_TIMINGS_=0
branches:
    only:
        - master
apt_packages:
    - r-cran-rjava
r_binary_packages:
    - checkmate
    - Rcpp
    - RcppEigen
    - testthat
    - knitr
    - ada
    - adabag
    - caret
    - class
    - clue
    - cluster
    - clusterSim
    - clValid
    - cmaes
    - CoxBoost
    - crs
    - Cubist
    - DiceKriging
    - e1071
    - earth
    - elasticnet
    - emoa
    - FNN
    - gbm
    - GenSA
    - glmnet
    - Hmisc
r_github_packages:
    - berndbischl/BBmisc
    - berndbischl/parallelMap
    - berndbischl/ParamHelpers
before_script:
    - sudo R CMD javareconf
    - java -cp /usr/local/lib/R/site-library/RWekajars/java/weka.jar weka.core.WekaPackageManager -install-package thirdparty/XMeans1.0.4.zip
notifications:
  email:
    recipients:
        - bernd_bischl@gmx.net
        - michellang@gmail.com
        - travis.mlr@jakob-r.de
        - larsko@cs.ubc.ca
        - schiffner@math.uni-duesseldorf.de
        - erich.studerus@gmail.com
    on_success: change
    on_failure: always
